### POST request to create patient
POST http://lb-20e42d7f.elb.localhost.localstack.cloud:4004/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "jk",
  "email": "jk1253a@jk1.com",
  "address": "123 jd street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

###